#ifndef SINFUNCTION_GLOBAL_H
#define SINFUNCTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SINFUNCTION_LIBRARY)
#  define SINFUNCTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SINFUNCTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SINFUNCTION_GLOBAL_H
